/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package purchasing;

import com.toedter.calendar.JDateChooser;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.InventoryModel;
import models.ProductModel;
import models.PurchasingDetailModel;
import models.PurchasingModel;
import models.WarehouseModel;

/**
 *
 * @author Windows 10
 */
public class PurchasingForm extends javax.swing.JFrame {
   PurchasingController purchasingController;
   DefaultTableModel tableModel;
   int currentPurchaseId =0;
   
   int grandtotal = 0;
   int subtotal = 0;
   
   public void displayCalculation(){
       Locale ID = new Locale("id","ID");
       NumberFormat numberFormat = NumberFormat.getCurrencyInstance(ID);
              
       subtotalDisplay.setText(numberFormat.format(subtotal));
       grandtotalDisplay.setText(numberFormat.format(grandtotal));
   }
   
   public void displayProductDetailTable(){
       try {
            
       } catch(Exception e){
           JOptionPane.showMessageDialog(null, "Gagal Menampilkan Data Pembelian Detail");
       }
   }
   
   public void setTableColumn(){
       tableModel.addColumn("No");
       tableModel.addColumn("Nama Produk");
       tableModel.addColumn("Harga");
       tableModel.addColumn("Jumlah");
       tableModel.addColumn("Subtotal");
   }
   
   public void displayPurchaseDetail(){
       try {
         ArrayList<PurchasingDetailModel> purchasingDetailItems = purchasingController.renderPurchaseDetails(currentPurchaseId);
         
         for(int i = 0; i < purchasingDetailItems.size(); i++){
             Object[] row = {
                 purchasingDetailItems.get(i).id,
                 purchasingDetailItems.get(i).productName,
                 purchasingDetailItems.get(i).productPrice,
                 purchasingDetailItems.get(i).qty,
                 purchasingDetailItems.get(i).subtotal,
             };
             
             
             tableModel.addRow(row);
         }
         
       } catch(Exception e){
         System.out.println(e.getMessage());
         JOptionPane.showMessageDialog(null,e.getMessage());
       }
   }
   
    /**
     * Creates new form PurchasingForm
     */
    public PurchasingForm() {
        initComponents();
        
        tableModel = new DefaultTableModel();
        
        this.setTableColumn();
                
        tableModel.setRowCount(0);
        
        purchaseDetailTable.setModel(tableModel);
        
        purchasingController = new PurchasingController();
        
        ArrayList<ProductModel> productItems = purchasingController.renderProducts();
        ArrayList<WarehouseModel> warehouseItems = purchasingController.renderWarehouses();
        
        for(int i = 0; i < productItems.size(); i++){
            String productName = productItems.get(i).name;
            int productId = productItems.get(i).id;
            String formatId = String.valueOf(productId);
            productSelects.addItem(formatId + " " + productName + " " + String.valueOf(productItems.get(i).price));
        }
        
        for(int j = 0; j < warehouseItems.size(); j++){
            String warehouseName = warehouseItems.get(j).name;
            int warehouseId = warehouseItems.get(j).id;
            String warehouseFormatted = String.valueOf(warehouseId);
            
            gudangSelects.addItem(warehouseFormatted + " " + warehouseName);
        }
        
        this.displayCalculation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        purchaseNumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        qty = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        purchaseDetailTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        subtotalDisplay = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        grandtotalDisplay = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        productSelects = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        gudangSelects = new javax.swing.JComboBox<>();
        purchaseDate = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton6.setText("Submit Pembelian");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Tambah Pembelian");

        jButton1.setText("Kembali");

        jLabel2.setText("Nomor Pembelian");

        jLabel3.setText("Pilih Produk");

        jLabel4.setText("Masukan Jumlah");

        jButton4.setText("Tambah Detail");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        purchaseDetailTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "Nama Produk", "Sku", "Harga", "Jumlah", "Subtotal"
            }
        ));
        jScrollPane2.setViewportView(purchaseDetailTable);

        jLabel5.setText("Subtotal");

        subtotalDisplay.setText("Rp. 0");

        jLabel7.setText("Grand Total");

        grandtotalDisplay.setText("Rp. 0");

        jButton7.setText("Selesaikan Pembelian");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel9.setText("Pilih Gudang");

        purchaseDate.setDateFormatString("yyyy-MM-dd");

        jLabel10.setText("Tanggal Beli");

        jButton2.setText("Buat Pembelian");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton5.setText("Bersihkan Keranjang");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(qty)
                            .addComponent(productSelects, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(gudangSelects, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(purchaseDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(purchaseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(subtotalDisplay))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(grandtotalDisplay))
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(purchaseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(productSelects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(gudangSelects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(purchaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(subtotalDisplay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(grandtotalDisplay))
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        
        String[] splitProductName = productSelects.getSelectedItem().toString().split(" ");
        String productSelected = splitProductName[0];
        String productSelectedPrice = splitProductName[splitProductName.length - 1];

        int productIdFormat = Integer.parseInt(productSelected);
        int qtyInput = Integer.parseInt(qty.getText());
       
        int subtotal = Integer.parseInt(productSelectedPrice) * qtyInput;
        int grandtotal = subtotal;
        
        this.subtotal += subtotal;
        this.grandtotal += grandtotal;
        
        PurchasingDetailModel purchasingDetailDto = new PurchasingDetailModel();
        
        purchasingDetailDto.createPurchasingDetail(subtotal, qtyInput, productIdFormat, subtotal, grandtotal, currentPurchaseId);
        
        boolean isDetailCreated = purchasingController.handleSubmitDetail(purchasingDetailDto);
        
        if(isDetailCreated){
            this.displayPurchaseDetail();
            this.displayCalculation();
            JOptionPane.showMessageDialog(null,"Berhasil Menambahkan Detail Pembelian");
        } else{
            JOptionPane.showMessageDialog(null,"Gagal Menambahkan Detail pembelian");
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        String purchaseNum = purchaseNumber.getText();
        String selectedWarehouse = gudangSelects.getSelectedItem().toString().split(" ")[0];
        int convertStr = Integer.parseInt(selectedWarehouse);
        Date selectedDate = purchaseDate.getDate();
        java.sql.Timestamp sqlTimestamp = new java.sql.Timestamp(selectedDate.getTime());

        
        PurchasingModel purchaseModel = new PurchasingModel();
        
        purchaseModel.createPurchasing(purchaseNum,convertStr,sqlTimestamp);
        int currentCreatedId = purchasingController.handleSubmit(purchaseModel);
        
        if(currentCreatedId > 0){
           this.currentPurchaseId = currentCreatedId;
           JOptionPane.showMessageDialog(null, "Berhasil Membuat Data Pembelian");
        } else {
           JOptionPane.showMessageDialog(null, "Gagal Membuat Data Pembelian");
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
         String[] warehouse = gudangSelects.getSelectedItem().toString().split(" ");
         int warehouseId = Integer.parseInt(warehouse[0]);
         ArrayList<PurchasingDetailModel> purchasingDetailItems = purchasingController.renderPurchaseDetails(currentPurchaseId);
         boolean isInventoryCreate = false;
        
         boolean isUpdatePurchase = purchasingController.handleUpdatePr(grandtotal, subtotal, currentPurchaseId);
         
         for(int j = 0; j < purchasingDetailItems.size(); j++){
            InventoryModel inventoryDto = new InventoryModel();
            int availableQty = purchasingDetailItems.get(j).qty;
            int productId = purchasingDetailItems.get(j).productId;
            inventoryDto.createInventory(warehouseId,availableQty,productId);
            boolean isCreated = purchasingController.handleCreateInventory(inventoryDto);
            isInventoryCreate = isCreated;
         }
         
         if(isInventoryCreate && isUpdatePurchase){
             JOptionPane.showMessageDialog(null,"Proses Pembelian Berhasil");
             this.currentPurchaseId=0;
             this.grandtotal = 0;
             this.subtotal = 0;
             
             this.tableModel.setRowCount(0);
             purchaseDetailTable.setModel(this.tableModel);
             
             new PurchasingForm().setVisible(false);
             new PurchasingIndex().setVisible(true);
             
         } else{
             JOptionPane.showMessageDialog(null,"Proses Pembelian Gagal Silahkan Coba Lagi");
         }
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        if(this.currentPurchaseId < 1){
            JOptionPane.showMessageDialog(null,"Tidak Ada Data Yang Perlu Dihapus");
        } else {
            boolean isDeleted = purchasingController.handleDeleteAll(currentPurchaseId);
            if(isDeleted){
              JOptionPane.showMessageDialog(null, "Berhasil Menghapus Pembelian Saat Ini");
              this.tableModel.setRowCount(0);
              this.setTableColumn();
              
              this.grandtotal=0;
              this.subtotal=0;
              this.displayCalculation();
            }
        }
    }//GEN-LAST:event_jButton5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PurchasingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PurchasingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PurchasingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PurchasingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PurchasingForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel grandtotalDisplay;
    private javax.swing.JComboBox<String> gudangSelects;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> productSelects;
    private com.toedter.calendar.JDateChooser purchaseDate;
    private javax.swing.JTable purchaseDetailTable;
    private javax.swing.JTextField purchaseNumber;
    private javax.swing.JTextField qty;
    private javax.swing.JLabel subtotalDisplay;
    // End of variables declaration//GEN-END:variables
}
