/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package components;

/**
 *
 * @author Asus
 */
public class NavigationBar extends javax.swing.JPanel {

    /**
     * Creates new form NavigationBar
     */
    public NavigationBar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homeLink = new javax.swing.JButton();
        produkLink = new javax.swing.JButton();
        supplierLink = new javax.swing.JButton();
        customerLink = new javax.swing.JButton();
        warehouseLink = new javax.swing.JButton();
        kategoriProdukLink = new javax.swing.JButton();
        paymentMethodLink = new javax.swing.JButton();
        penjualanLink = new javax.swing.JButton();
        pembelianLink = new javax.swing.JButton();
        penyimpananLink = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 255));

        homeLink.setText("Home");

        produkLink.setText("Produk");
        produkLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                produkLinkMouseClicked(evt);
            }
        });

        supplierLink.setText("Supplier");

        customerLink.setText("Customer");

        warehouseLink.setText("Warehouse");

        kategoriProdukLink.setText("Kategori Produk");

        paymentMethodLink.setText("Metode Pembayaran");

        penjualanLink.setText("Penjualan");

        pembelianLink.setText("Pembelian");

        penyimpananLink.setText("Penyimpanan");
        penyimpananLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penyimpananLinkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(penjualanLink)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pembelianLink)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(penyimpananLink))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(homeLink)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(produkLink)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(supplierLink)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customerLink)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(warehouseLink)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kategoriProdukLink)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(paymentMethodLink)))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homeLink)
                    .addComponent(produkLink)
                    .addComponent(supplierLink)
                    .addComponent(customerLink)
                    .addComponent(warehouseLink)
                    .addComponent(kategoriProdukLink)
                    .addComponent(paymentMethodLink))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(penjualanLink)
                    .addComponent(pembelianLink)
                    .addComponent(penyimpananLink))
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void penyimpananLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penyimpananLinkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_penyimpananLinkActionPerformed

    private void produkLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_produkLinkMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_produkLinkMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton customerLink;
    private javax.swing.JButton homeLink;
    private javax.swing.JButton kategoriProdukLink;
    private javax.swing.JButton paymentMethodLink;
    private javax.swing.JButton pembelianLink;
    private javax.swing.JButton penjualanLink;
    private javax.swing.JButton penyimpananLink;
    private javax.swing.JButton produkLink;
    private javax.swing.JButton supplierLink;
    private javax.swing.JButton warehouseLink;
    // End of variables declaration//GEN-END:variables
}
